#!/bin/bash
keyring="archlinuxcn-keyring"
zlkDE="sddm awesome xcompmgr transset-df conky xscreensaver pcmanfm notepadqq google-chrome xfce4-terminal"
tools="git-lfs sshfs pkgfile mlocate net-tools lshw scrot xorg-xrandr wget git shadowsocks screenfetch lxappearance feh fcitx-sogoupinyin dosfstools ntfs-3g fcitx-configtool"
entertainments="ktorrent netease-cloud-music smplayer"
devel="gdb emacs-git docker"
AUR="gtk-theme-arc-git mac-os-lion-cursors macos-icon-theme acroread"
offonts="wqy-zenhei ttf-inconsolata"
aurfonts="consolas-font"
deamon="at cronie"
mydir="~/Downloads ~/Documents ~/Pictures ~/Desktop ~/Workspace"
pacman -Syu --noconfirm yaourt
pacman -S --noconfirm $keyring $zlkDE $tools $entertainments $devel $offonts
yaourt -S --noconfirm $AUR $aurfonts
