#!/bin/bash
ip=$1;
port=$2;
password=$3;
echo {
echo "  \"server\": \"$ip\","
echo "  \"server_port\":$port,"
echo "  \"local_address\":\"127.0.0.1\","
echo "  \"local_port\":8080,"
echo "  \"password\":\"$password\","
echo "  \"timeout\":300,"
echo "  \"method\":\"aes-256-cfb\","
echo "  \"fast_open\":true,"
echo "  \"workers\":20"
echo }
